site_name: INNAKM
theme:
  name: material

  icon:
    repo: fontawesome/brands/git-alt

  logo: ./assets/logo_full_4.png

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.path
    
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  language: en

repo_name: INNAKM Repository
repo_url: https://github.com/fikridean/INNAKM